### PR TITLE
REQUEST FOR CODE REVIEW ON RAILS SOCIAL MEDIA PROJECT:MILESTONE 3 - FRIENDSHIPS-V2

### PR DESCRIPTION
**Pull request by Moreneecoder**
In this project, I refactored the logic of the #accept_friendships method in the User model to hold mutual friendship data in two rows for more efficiency. I also refactored the #friends method in the User model to more efficiently fetch mutual friendships from the database. 

Also, I refactored the RSpec unit tests for the aforementioned methods.

> IMPORTANT: Please run `rails db:reset` before migrating. I had review issues with the last two TSEs as a `relation already exists` error occurred. The `rails db:reset` command fixed this after troubleshooting with the last reviewer.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: INVALID :red_circle: 

**Hi @Moreneecoder**
There is a migration issue, due to which I can't review the project. please fix this issue and re-submit for review.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Moreneecoder** [comment]
The last reviewer invalidated my submission due to migration problems but he didn't state what the problem was exactly. I troubleshooter this error and tried to run `rails db:create` and `rails db:migrate` on a new database name in my database config file. This works perfectly. Please if you encounter the same issue - which I doubt - kindly state what the actual problem is. Thank you.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## STATUS: INVALID! :exclamation:
### Hi @Moreneecoder    ! :wave: :wave:

#### Hello there, I have to invalidate your project due to migration issues as said by the previous TSE. On running `rails db:migrate` I get this error:
```
== 20210430203600 CreateFriendships: migrating ================================
-- create_table(:friendships)
rails aborted!
StandardError: An error has occurred, this and all later migrations cancelled:

PG::DuplicateTable: ERROR:  relation "friendships" already exists
: CREATE TABLE "friendships" ("id" bigserial primary key, "user_id" bigint, "friend_id" bigint, "status" boolean, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_e3733b59b7"
FOREIGN KEY ("user_id")
  REFER
```
Following the steps, you listed above makes no difference as well. kindly look into this issue, fix it and submit it for review.

_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 
- Great work fixing your database issues.
- Impressive work getting the double row friendship model correct! Students usually struggle with this concept but you got this right. Congrats!

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
